security:
  oauth2:
    client:
      clientId: 1223784957953901
      clientSecret: 0c6caa062761771ebd559d778c02e7a3
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me